# cookie_secret_and_proxy_auth_token.yml
# see https://professorkazarinoff.github.io/jupyterhub-engr101/cookie_secret_proxy_auth_token/
---
- hosts: all
  remote_user: root
  gather_facts: false

  tasks:
    - name: create /srv/jupyterhub directory
      file:
        path: /srv/jupyterhub
        mode: 0550
        recurse: yes
        state: directory
        group: peter
      become: yes

    - name: touch/create jupyterhub_cookie_secret file
      file:
        path: /srv/jupyterhub/jupyterhub_cookie_secret
        mode: 0600
        recurse: yes
        group: sudo
      become: yes

    - name: use open ssl to generate cookie secret file
      shell: sudo openssl rand -hex 32 > /srv/jupyterhub/jupyterhub_cookie_secret
      become: yes

    - name: touch/create proxy auth token file
      file:
        path: /srv/jupyterhub/proxy_auth_token
        mode: 0600
        group: sudo
      become: yes

    - name: use open ssl to generate proxy auth token file
      shell: sudo openssl rand -hex 32 > /srv/jupyterhub/proxy_auth_token
      become: yes

    - name: touch/create dhparam.pem file
      file:
        path: /srv/jupyterhub/dhparam.pem
        mode: 0600
        group: sudo
      become: yes

    - name: use open ssl to generate dhparam.pem file
      shell: sudo openssl dhparam -out /srv/jupyterhub/dhparam.pem 2048
      become: yes
