# get_do_server_info.yml
---
- hosts: all
  remote_user: root
  gather_facts: true
  
  tasks:
    - name: Include vars from vars.yml file
      include_vars:
        file: vars.yml
    - name: Gather information about all droplet sizes
      digital_ocean_size_info:
        oauth_token: "{{ do_api_key }}"
      register: resp_out
    - debug: var=resp_out
