# site.yml
# master playbook that runs other playbooks
- import_playbook: initial_server_setup.yml
- import_playbook: install_miniconda.yml
- import_playbook: install_jupyterhub.yml
#- import_playbook: ssl_cirt.yml
