# site.yml
#
# master Ansible playbook that runs all the other playbooks
---
---
# file: site.yml
- import_playbook: initial_server_setup.yml
- import_playbook: install_miniconda.yml
- import_playbook: install_jupyterhub.yml
- import_playbook: ssl_cirt.yml
